### ISSUE TITLE
change path where webworker is loaded

### ISSUE THREAD

**Issue by bautistaaa** [UIUXEngineering/web-worker-in-ng#4]
Hey(I'm back haha),

Have you ran into a situation where you need to change where the worker is loaded from. Right now it seems to just load from the root but what if i wanted to load from 'test/workers/' instead? I went through the worker-loader docs and none of the webpack config stuff seems to be working(i think I may need to eject it which I want to avoid).

Any ideas?

Thanks!

**Comment by bautistaaa** [comment]
nm i ended up forking the worker loader library and change the public path myself. based on the environment prod variable ill use either my fork or the original worker loader module.. HACK!

**Comment by jerryorta-dev** [comment]
Not sure if I understand. But...the relative paths in both [webpack.worker.config.js](https://github.com/UIUXEngineering/web-worker-in-ng/blob/master/webpack.worker.config.js#L24) and [`src/app/services/web-worker.service.ts`](https://github.com/UIUXEngineering/web-worker-in-ng/blob/master/src/app/services/web-worker.service.ts#L2) or for webpack's configuration. When the app builds in both dev and prod, webpack resolves the path relative to the app files and writes those paths instead of what is actually hard coded.

**Comment by bautistaaa** [comment]
Not sure how I can explain this better. 

Example:
I run ng serve --prod. All files are all at the same level in dist. However for our prod build we move the js files to different folders(web/scripts/) so the compiled worker js would go in there and the typical bundled stuff. When I launch the application with this folder structure it is still trying to find the worker at my-url:1234/1235123.worker.js when in reality it is at my-url:1234/web/scripts/1235123.worker.js. I couldn't figure out how to make that happen.
